import { FileType } from '../type/FileType';

export const Files: FileType[] = [
    {
        id: '525CD328E917',
        name: 'file name 1',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '8FF4315054B1',
        name: 'file name 2',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'FD617D70DAF9',
        name: 'file name 3',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '2A6D93A8C8CB',
        name: 'file name 4',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'E6D49E3E1839',
        name: 'file name 5',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'D6B2152C0456',
        name: 'file name 6',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '9C98044616EB',
        name: 'file name 7',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '5D9691DA55EF',
        name: 'file name 8',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'E405A071230F',
        name: 'file name 9',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'B948D441F363',
        name: 'file name 10',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'E01C7BA3A42A',
        name: 'file name 11',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '4466C81CD7A6',
        name: 'file name 12',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '06299E5073BA',
        name: 'file name 13',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'DC451D9D3945',
        name: 'file name 14',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '5CEE66FAA6F9',
        name: 'file name 15',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '9BF8BCEBC98E',
        name: 'file name 16',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'F18D01CEFB25',
        name: 'file name 17',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '61128F45363C',
        name: 'file name 18',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'F9809C7DC924',
        name: 'file name 19',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '030E3E41E87A',
        name: 'file name 20',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '58877CBF5489',
        name: 'file name 21',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '5CBF6EBC6F81',
        name: 'file name 22',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '776368BD195F',
        name: 'file name 23',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'F1A9C1CE382C',
        name: 'file name 24',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '37E64F66F4E9',
        name: 'file name 25',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'EB5D49FBDA6D',
        name: 'file name 26',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: 'FAAFD5F66C32',
        name: 'file name 27',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '8AB9A6DBA681',
        name: 'file name 28',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '5952C1E0E08D',
        name: 'file name 29',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])},
        {
        id: '5591FAEE2F10',
        name: 'file name 30',
        content: new Map([
            ['key1', 'value1'],
            ['key2', 'value2'],
            ['key3', 'value3'],
            ['key4', 'value4'],
            ['key5', 'value5'],
            ['key6', 'value6'],
            ['key7', 'value7'],
            ['key8', 'value8'],
            ['key9', 'value9'],
            ['key10', 'value10'],
            ['key11', 'value11'],
            ['key12', 'value12'],
            ['key13', 'value13'],
            ['key14', 'value14'],
            ['key15', 'value15'],
            ['key16', 'value16'],
            ['key17', 'value17'],
            ['key18', 'value18'],
            ['key19', 'value19'],
            ['key20', 'value20']
        ])}
];
